load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "enums",
    srcs = [
        "lib.go",
        "lib_string.go",
    ],
    importpath = "github.com/nobu-k/bazel-go-test/enums",
    visibility = ["//visibility:public"],
)
